/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthSsoRouteImport } from './routes/auth/sso'
import { Route as AuthDevTicketRouteImport } from './routes/auth/dev-ticket'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardMailRouteRouteImport } from './routes/_dashboard/mail/route'
import { Route as DashboardSubordinatesIndexRouteImport } from './routes/_dashboard/subordinates/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/_dashboard/profile/index'
import { Route as DashboardMailUserMailsIndexRouteImport } from './routes/_dashboard/mail/user-mails/index'
import { Route as DashboardMailUserMailsCreateRouteImport } from './routes/_dashboard/mail/user-mails/create'
import { Route as DashboardMailUserMailsComposeRouteImport } from './routes/_dashboard/mail/user-mails/compose'
import { Route as DashboardMailUserMailsMailIdEditNonTemplateRouteImport } from './routes/_dashboard/mail/user-mails/$mailId.edit-non-template'
import { Route as DashboardMailUserMailsMailIdEditRouteImport } from './routes/_dashboard/mail/user-mails/$mailId.edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSsoRoute = AuthSsoRouteImport.update({
  id: '/auth/sso',
  path: '/auth/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDevTicketRoute = AuthDevTicketRouteImport.update({
  id: '/auth/dev-ticket',
  path: '/auth/dev-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailRouteRoute = DashboardMailRouteRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubordinatesIndexRoute =
  DashboardSubordinatesIndexRouteImport.update({
    id: '/subordinates/',
    path: '/subordinates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailUserMailsIndexRoute =
  DashboardMailUserMailsIndexRouteImport.update({
    id: '/user-mails/',
    path: '/user-mails/',
    getParentRoute: () => DashboardMailRouteRoute,
  } as any)
const DashboardMailUserMailsCreateRoute =
  DashboardMailUserMailsCreateRouteImport.update({
    id: '/user-mails/create',
    path: '/user-mails/create',
    getParentRoute: () => DashboardMailRouteRoute,
  } as any)
const DashboardMailUserMailsComposeRoute =
  DashboardMailUserMailsComposeRouteImport.update({
    id: '/user-mails/compose',
    path: '/user-mails/compose',
    getParentRoute: () => DashboardMailRouteRoute,
  } as any)
const DashboardMailUserMailsMailIdEditNonTemplateRoute =
  DashboardMailUserMailsMailIdEditNonTemplateRouteImport.update({
    id: '/user-mails/$mailId/edit-non-template',
    path: '/user-mails/$mailId/edit-non-template',
    getParentRoute: () => DashboardMailRouteRoute,
  } as any)
const DashboardMailUserMailsMailIdEditRoute =
  DashboardMailUserMailsMailIdEditRouteImport.update({
    id: '/user-mails/$mailId/edit',
    path: '/user-mails/$mailId/edit',
    getParentRoute: () => DashboardMailRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/mail': typeof DashboardMailRouteRouteWithChildren
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/dev-ticket': typeof AuthDevTicketRoute
  '/auth/sso': typeof AuthSsoRoute
  '/profile/': typeof DashboardProfileIndexRoute
  '/subordinates/': typeof DashboardSubordinatesIndexRoute
  '/mail/user-mails/compose': typeof DashboardMailUserMailsComposeRoute
  '/mail/user-mails/create': typeof DashboardMailUserMailsCreateRoute
  '/mail/user-mails/': typeof DashboardMailUserMailsIndexRoute
  '/mail/user-mails/$mailId/edit': typeof DashboardMailUserMailsMailIdEditRoute
  '/mail/user-mails/$mailId/edit-non-template': typeof DashboardMailUserMailsMailIdEditNonTemplateRoute
}
export interface FileRoutesByTo {
  '/mail': typeof DashboardMailRouteRouteWithChildren
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/dev-ticket': typeof AuthDevTicketRoute
  '/auth/sso': typeof AuthSsoRoute
  '/': typeof DashboardIndexRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/subordinates': typeof DashboardSubordinatesIndexRoute
  '/mail/user-mails/compose': typeof DashboardMailUserMailsComposeRoute
  '/mail/user-mails/create': typeof DashboardMailUserMailsCreateRoute
  '/mail/user-mails': typeof DashboardMailUserMailsIndexRoute
  '/mail/user-mails/$mailId/edit': typeof DashboardMailUserMailsMailIdEditRoute
  '/mail/user-mails/$mailId/edit-non-template': typeof DashboardMailUserMailsMailIdEditNonTemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/mail': typeof DashboardMailRouteRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/auth/dev-ticket': typeof AuthDevTicketRoute
  '/auth/sso': typeof AuthSsoRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/profile/': typeof DashboardProfileIndexRoute
  '/_dashboard/subordinates/': typeof DashboardSubordinatesIndexRoute
  '/_dashboard/mail/user-mails/compose': typeof DashboardMailUserMailsComposeRoute
  '/_dashboard/mail/user-mails/create': typeof DashboardMailUserMailsCreateRoute
  '/_dashboard/mail/user-mails/': typeof DashboardMailUserMailsIndexRoute
  '/_dashboard/mail/user-mails/$mailId/edit': typeof DashboardMailUserMailsMailIdEditRoute
  '/_dashboard/mail/user-mails/$mailId/edit-non-template': typeof DashboardMailUserMailsMailIdEditNonTemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mail'
    | '/dashboard'
    | '/auth/dev-ticket'
    | '/auth/sso'
    | '/profile/'
    | '/subordinates/'
    | '/mail/user-mails/compose'
    | '/mail/user-mails/create'
    | '/mail/user-mails/'
    | '/mail/user-mails/$mailId/edit'
    | '/mail/user-mails/$mailId/edit-non-template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mail'
    | '/dashboard'
    | '/auth/dev-ticket'
    | '/auth/sso'
    | '/'
    | '/profile'
    | '/subordinates'
    | '/mail/user-mails/compose'
    | '/mail/user-mails/create'
    | '/mail/user-mails'
    | '/mail/user-mails/$mailId/edit'
    | '/mail/user-mails/$mailId/edit-non-template'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/mail'
    | '/_dashboard/dashboard'
    | '/auth/dev-ticket'
    | '/auth/sso'
    | '/_dashboard/'
    | '/_dashboard/profile/'
    | '/_dashboard/subordinates/'
    | '/_dashboard/mail/user-mails/compose'
    | '/_dashboard/mail/user-mails/create'
    | '/_dashboard/mail/user-mails/'
    | '/_dashboard/mail/user-mails/$mailId/edit'
    | '/_dashboard/mail/user-mails/$mailId/edit-non-template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthDevTicketRoute: typeof AuthDevTicketRoute
  AuthSsoRoute: typeof AuthSsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/sso': {
      id: '/auth/sso'
      path: '/auth/sso'
      fullPath: '/auth/sso'
      preLoaderRoute: typeof AuthSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dev-ticket': {
      id: '/auth/dev-ticket'
      path: '/auth/dev-ticket'
      fullPath: '/auth/dev-ticket'
      preLoaderRoute: typeof AuthDevTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail': {
      id: '/_dashboard/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof DashboardMailRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/subordinates/': {
      id: '/_dashboard/subordinates/'
      path: '/subordinates'
      fullPath: '/subordinates/'
      preLoaderRoute: typeof DashboardSubordinatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile/': {
      id: '/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/user-mails/': {
      id: '/_dashboard/mail/user-mails/'
      path: '/user-mails'
      fullPath: '/mail/user-mails/'
      preLoaderRoute: typeof DashboardMailUserMailsIndexRouteImport
      parentRoute: typeof DashboardMailRouteRoute
    }
    '/_dashboard/mail/user-mails/create': {
      id: '/_dashboard/mail/user-mails/create'
      path: '/user-mails/create'
      fullPath: '/mail/user-mails/create'
      preLoaderRoute: typeof DashboardMailUserMailsCreateRouteImport
      parentRoute: typeof DashboardMailRouteRoute
    }
    '/_dashboard/mail/user-mails/compose': {
      id: '/_dashboard/mail/user-mails/compose'
      path: '/user-mails/compose'
      fullPath: '/mail/user-mails/compose'
      preLoaderRoute: typeof DashboardMailUserMailsComposeRouteImport
      parentRoute: typeof DashboardMailRouteRoute
    }
    '/_dashboard/mail/user-mails/$mailId/edit-non-template': {
      id: '/_dashboard/mail/user-mails/$mailId/edit-non-template'
      path: '/user-mails/$mailId/edit-non-template'
      fullPath: '/mail/user-mails/$mailId/edit-non-template'
      preLoaderRoute: typeof DashboardMailUserMailsMailIdEditNonTemplateRouteImport
      parentRoute: typeof DashboardMailRouteRoute
    }
    '/_dashboard/mail/user-mails/$mailId/edit': {
      id: '/_dashboard/mail/user-mails/$mailId/edit'
      path: '/user-mails/$mailId/edit'
      fullPath: '/mail/user-mails/$mailId/edit'
      preLoaderRoute: typeof DashboardMailUserMailsMailIdEditRouteImport
      parentRoute: typeof DashboardMailRouteRoute
    }
  }
}

interface DashboardMailRouteRouteChildren {
  DashboardMailUserMailsComposeRoute: typeof DashboardMailUserMailsComposeRoute
  DashboardMailUserMailsCreateRoute: typeof DashboardMailUserMailsCreateRoute
  DashboardMailUserMailsIndexRoute: typeof DashboardMailUserMailsIndexRoute
  DashboardMailUserMailsMailIdEditRoute: typeof DashboardMailUserMailsMailIdEditRoute
  DashboardMailUserMailsMailIdEditNonTemplateRoute: typeof DashboardMailUserMailsMailIdEditNonTemplateRoute
}

const DashboardMailRouteRouteChildren: DashboardMailRouteRouteChildren = {
  DashboardMailUserMailsComposeRoute: DashboardMailUserMailsComposeRoute,
  DashboardMailUserMailsCreateRoute: DashboardMailUserMailsCreateRoute,
  DashboardMailUserMailsIndexRoute: DashboardMailUserMailsIndexRoute,
  DashboardMailUserMailsMailIdEditRoute: DashboardMailUserMailsMailIdEditRoute,
  DashboardMailUserMailsMailIdEditNonTemplateRoute:
    DashboardMailUserMailsMailIdEditNonTemplateRoute,
}

const DashboardMailRouteRouteWithChildren =
  DashboardMailRouteRoute._addFileChildren(DashboardMailRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardMailRouteRoute: typeof DashboardMailRouteRouteWithChildren
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSubordinatesIndexRoute: typeof DashboardSubordinatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMailRouteRoute: DashboardMailRouteRouteWithChildren,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSubordinatesIndexRoute: DashboardSubordinatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthDevTicketRoute: AuthDevTicketRoute,
  AuthSsoRoute: AuthSsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
