/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthSsoRouteImport } from './routes/auth/sso'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardSystemUsersRouteImport } from './routes/_dashboard/system/users'
import { Route as DashboardSystemRolesRouteImport } from './routes/_dashboard/system/roles'
import { Route as DashboardMasterStaffsRouteImport } from './routes/_dashboard/master/staffs'
import { Route as DashboardMasterPositionsRouteImport } from './routes/_dashboard/master/positions'
import { Route as DashboardMasterDepartmentsRouteImport } from './routes/_dashboard/master/departments'
import { Route as DashboardMasterBranchesRouteImport } from './routes/_dashboard/master/branches'
import { Route as DashboardMasterAreasRouteImport } from './routes/_dashboard/master/areas'
import { Route as DashboardMailDynamicMailTemplatesRouteImport } from './routes/_dashboard/mail/dynamic-mail-templates'
import { Route as DashboardMailAllMailsRouteImport } from './routes/_dashboard/mail/all-mails'
import { Route as DashboardMailStaticMailTemplatesIndexRouteImport } from './routes/_dashboard/mail/static-mail-templates/index'
import { Route as DashboardMailDynamicMailTemplatesIndexRouteImport } from './routes/_dashboard/mail/dynamic-mail-templates/index'
import { Route as DashboardMailStaticMailTemplatesCreateRouteImport } from './routes/_dashboard/mail/static-mail-templates/create'
import { Route as DashboardMailDynamicMailTemplatesCreateRouteImport } from './routes/_dashboard/mail/dynamic-mail-templates/create'
import { Route as DashboardMailStaticMailTemplatesIdIndexRouteImport } from './routes/_dashboard/mail/static-mail-templates/$id/index'
import { Route as DashboardMailDynamicMailTemplatesIdIndexRouteImport } from './routes/_dashboard/mail/dynamic-mail-templates/$id/index'
import { Route as DashboardMailStaticMailTemplatesIdEditRouteImport } from './routes/_dashboard/mail/static-mail-templates/$id/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSsoRoute = AuthSsoRouteImport.update({
  id: '/auth/sso',
  path: '/auth/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemUsersRoute = DashboardSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemRolesRoute = DashboardSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMasterStaffsRoute = DashboardMasterStaffsRouteImport.update({
  id: '/master/staffs',
  path: '/master/staffs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMasterPositionsRoute =
  DashboardMasterPositionsRouteImport.update({
    id: '/master/positions',
    path: '/master/positions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMasterDepartmentsRoute =
  DashboardMasterDepartmentsRouteImport.update({
    id: '/master/departments',
    path: '/master/departments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMasterBranchesRoute = DashboardMasterBranchesRouteImport.update({
  id: '/master/branches',
  path: '/master/branches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMasterAreasRoute = DashboardMasterAreasRouteImport.update({
  id: '/master/areas',
  path: '/master/areas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailDynamicMailTemplatesRoute =
  DashboardMailDynamicMailTemplatesRouteImport.update({
    id: '/mail/dynamic-mail-templates',
    path: '/mail/dynamic-mail-templates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMailAllMailsRoute = DashboardMailAllMailsRouteImport.update({
  id: '/mail/all-mails',
  path: '/mail/all-mails',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailStaticMailTemplatesIndexRoute =
  DashboardMailStaticMailTemplatesIndexRouteImport.update({
    id: '/mail/static-mail-templates/',
    path: '/mail/static-mail-templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMailDynamicMailTemplatesIndexRoute =
  DashboardMailDynamicMailTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMailDynamicMailTemplatesRoute,
  } as any)
const DashboardMailStaticMailTemplatesCreateRoute =
  DashboardMailStaticMailTemplatesCreateRouteImport.update({
    id: '/mail/static-mail-templates/create',
    path: '/mail/static-mail-templates/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMailDynamicMailTemplatesCreateRoute =
  DashboardMailDynamicMailTemplatesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardMailDynamicMailTemplatesRoute,
  } as any)
const DashboardMailStaticMailTemplatesIdIndexRoute =
  DashboardMailStaticMailTemplatesIdIndexRouteImport.update({
    id: '/mail/static-mail-templates/$id/',
    path: '/mail/static-mail-templates/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMailDynamicMailTemplatesIdIndexRoute =
  DashboardMailDynamicMailTemplatesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => DashboardMailDynamicMailTemplatesRoute,
  } as any)
const DashboardMailStaticMailTemplatesIdEditRoute =
  DashboardMailStaticMailTemplatesIdEditRouteImport.update({
    id: '/mail/static-mail-templates/$id/edit',
    path: '/mail/static-mail-templates/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/sso': typeof AuthSsoRoute
  '/mail/all-mails': typeof DashboardMailAllMailsRoute
  '/mail/dynamic-mail-templates': typeof DashboardMailDynamicMailTemplatesRouteWithChildren
  '/master/areas': typeof DashboardMasterAreasRoute
  '/master/branches': typeof DashboardMasterBranchesRoute
  '/master/departments': typeof DashboardMasterDepartmentsRoute
  '/master/positions': typeof DashboardMasterPositionsRoute
  '/master/staffs': typeof DashboardMasterStaffsRoute
  '/system/roles': typeof DashboardSystemRolesRoute
  '/system/users': typeof DashboardSystemUsersRoute
  '/mail/dynamic-mail-templates/create': typeof DashboardMailDynamicMailTemplatesCreateRoute
  '/mail/static-mail-templates/create': typeof DashboardMailStaticMailTemplatesCreateRoute
  '/mail/dynamic-mail-templates/': typeof DashboardMailDynamicMailTemplatesIndexRoute
  '/mail/static-mail-templates/': typeof DashboardMailStaticMailTemplatesIndexRoute
  '/mail/static-mail-templates/$id/edit': typeof DashboardMailStaticMailTemplatesIdEditRoute
  '/mail/dynamic-mail-templates/$id/': typeof DashboardMailDynamicMailTemplatesIdIndexRoute
  '/mail/static-mail-templates/$id/': typeof DashboardMailStaticMailTemplatesIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardDashboardRoute
  '/auth/sso': typeof AuthSsoRoute
  '/': typeof DashboardIndexRoute
  '/mail/all-mails': typeof DashboardMailAllMailsRoute
  '/master/areas': typeof DashboardMasterAreasRoute
  '/master/branches': typeof DashboardMasterBranchesRoute
  '/master/departments': typeof DashboardMasterDepartmentsRoute
  '/master/positions': typeof DashboardMasterPositionsRoute
  '/master/staffs': typeof DashboardMasterStaffsRoute
  '/system/roles': typeof DashboardSystemRolesRoute
  '/system/users': typeof DashboardSystemUsersRoute
  '/mail/dynamic-mail-templates/create': typeof DashboardMailDynamicMailTemplatesCreateRoute
  '/mail/static-mail-templates/create': typeof DashboardMailStaticMailTemplatesCreateRoute
  '/mail/dynamic-mail-templates': typeof DashboardMailDynamicMailTemplatesIndexRoute
  '/mail/static-mail-templates': typeof DashboardMailStaticMailTemplatesIndexRoute
  '/mail/static-mail-templates/$id/edit': typeof DashboardMailStaticMailTemplatesIdEditRoute
  '/mail/dynamic-mail-templates/$id': typeof DashboardMailDynamicMailTemplatesIdIndexRoute
  '/mail/static-mail-templates/$id': typeof DashboardMailStaticMailTemplatesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/auth/sso': typeof AuthSsoRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/mail/all-mails': typeof DashboardMailAllMailsRoute
  '/_dashboard/mail/dynamic-mail-templates': typeof DashboardMailDynamicMailTemplatesRouteWithChildren
  '/_dashboard/master/areas': typeof DashboardMasterAreasRoute
  '/_dashboard/master/branches': typeof DashboardMasterBranchesRoute
  '/_dashboard/master/departments': typeof DashboardMasterDepartmentsRoute
  '/_dashboard/master/positions': typeof DashboardMasterPositionsRoute
  '/_dashboard/master/staffs': typeof DashboardMasterStaffsRoute
  '/_dashboard/system/roles': typeof DashboardSystemRolesRoute
  '/_dashboard/system/users': typeof DashboardSystemUsersRoute
  '/_dashboard/mail/dynamic-mail-templates/create': typeof DashboardMailDynamicMailTemplatesCreateRoute
  '/_dashboard/mail/static-mail-templates/create': typeof DashboardMailStaticMailTemplatesCreateRoute
  '/_dashboard/mail/dynamic-mail-templates/': typeof DashboardMailDynamicMailTemplatesIndexRoute
  '/_dashboard/mail/static-mail-templates/': typeof DashboardMailStaticMailTemplatesIndexRoute
  '/_dashboard/mail/static-mail-templates/$id/edit': typeof DashboardMailStaticMailTemplatesIdEditRoute
  '/_dashboard/mail/dynamic-mail-templates/$id/': typeof DashboardMailDynamicMailTemplatesIdIndexRoute
  '/_dashboard/mail/static-mail-templates/$id/': typeof DashboardMailStaticMailTemplatesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/sso'
    | '/mail/all-mails'
    | '/mail/dynamic-mail-templates'
    | '/master/areas'
    | '/master/branches'
    | '/master/departments'
    | '/master/positions'
    | '/master/staffs'
    | '/system/roles'
    | '/system/users'
    | '/mail/dynamic-mail-templates/create'
    | '/mail/static-mail-templates/create'
    | '/mail/dynamic-mail-templates/'
    | '/mail/static-mail-templates/'
    | '/mail/static-mail-templates/$id/edit'
    | '/mail/dynamic-mail-templates/$id/'
    | '/mail/static-mail-templates/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/auth/sso'
    | '/'
    | '/mail/all-mails'
    | '/master/areas'
    | '/master/branches'
    | '/master/departments'
    | '/master/positions'
    | '/master/staffs'
    | '/system/roles'
    | '/system/users'
    | '/mail/dynamic-mail-templates/create'
    | '/mail/static-mail-templates/create'
    | '/mail/dynamic-mail-templates'
    | '/mail/static-mail-templates'
    | '/mail/static-mail-templates/$id/edit'
    | '/mail/dynamic-mail-templates/$id'
    | '/mail/static-mail-templates/$id'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/dashboard'
    | '/auth/sso'
    | '/_dashboard/'
    | '/_dashboard/mail/all-mails'
    | '/_dashboard/mail/dynamic-mail-templates'
    | '/_dashboard/master/areas'
    | '/_dashboard/master/branches'
    | '/_dashboard/master/departments'
    | '/_dashboard/master/positions'
    | '/_dashboard/master/staffs'
    | '/_dashboard/system/roles'
    | '/_dashboard/system/users'
    | '/_dashboard/mail/dynamic-mail-templates/create'
    | '/_dashboard/mail/static-mail-templates/create'
    | '/_dashboard/mail/dynamic-mail-templates/'
    | '/_dashboard/mail/static-mail-templates/'
    | '/_dashboard/mail/static-mail-templates/$id/edit'
    | '/_dashboard/mail/dynamic-mail-templates/$id/'
    | '/_dashboard/mail/static-mail-templates/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthSsoRoute: typeof AuthSsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/sso': {
      id: '/auth/sso'
      path: '/auth/sso'
      fullPath: '/auth/sso'
      preLoaderRoute: typeof AuthSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/system/users': {
      id: '/_dashboard/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof DashboardSystemUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/system/roles': {
      id: '/_dashboard/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof DashboardSystemRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/master/staffs': {
      id: '/_dashboard/master/staffs'
      path: '/master/staffs'
      fullPath: '/master/staffs'
      preLoaderRoute: typeof DashboardMasterStaffsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/master/positions': {
      id: '/_dashboard/master/positions'
      path: '/master/positions'
      fullPath: '/master/positions'
      preLoaderRoute: typeof DashboardMasterPositionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/master/departments': {
      id: '/_dashboard/master/departments'
      path: '/master/departments'
      fullPath: '/master/departments'
      preLoaderRoute: typeof DashboardMasterDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/master/branches': {
      id: '/_dashboard/master/branches'
      path: '/master/branches'
      fullPath: '/master/branches'
      preLoaderRoute: typeof DashboardMasterBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/master/areas': {
      id: '/_dashboard/master/areas'
      path: '/master/areas'
      fullPath: '/master/areas'
      preLoaderRoute: typeof DashboardMasterAreasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/dynamic-mail-templates': {
      id: '/_dashboard/mail/dynamic-mail-templates'
      path: '/mail/dynamic-mail-templates'
      fullPath: '/mail/dynamic-mail-templates'
      preLoaderRoute: typeof DashboardMailDynamicMailTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/all-mails': {
      id: '/_dashboard/mail/all-mails'
      path: '/mail/all-mails'
      fullPath: '/mail/all-mails'
      preLoaderRoute: typeof DashboardMailAllMailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/static-mail-templates/': {
      id: '/_dashboard/mail/static-mail-templates/'
      path: '/mail/static-mail-templates'
      fullPath: '/mail/static-mail-templates/'
      preLoaderRoute: typeof DashboardMailStaticMailTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/dynamic-mail-templates/': {
      id: '/_dashboard/mail/dynamic-mail-templates/'
      path: '/'
      fullPath: '/mail/dynamic-mail-templates/'
      preLoaderRoute: typeof DashboardMailDynamicMailTemplatesIndexRouteImport
      parentRoute: typeof DashboardMailDynamicMailTemplatesRoute
    }
    '/_dashboard/mail/static-mail-templates/create': {
      id: '/_dashboard/mail/static-mail-templates/create'
      path: '/mail/static-mail-templates/create'
      fullPath: '/mail/static-mail-templates/create'
      preLoaderRoute: typeof DashboardMailStaticMailTemplatesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/dynamic-mail-templates/create': {
      id: '/_dashboard/mail/dynamic-mail-templates/create'
      path: '/create'
      fullPath: '/mail/dynamic-mail-templates/create'
      preLoaderRoute: typeof DashboardMailDynamicMailTemplatesCreateRouteImport
      parentRoute: typeof DashboardMailDynamicMailTemplatesRoute
    }
    '/_dashboard/mail/static-mail-templates/$id/': {
      id: '/_dashboard/mail/static-mail-templates/$id/'
      path: '/mail/static-mail-templates/$id'
      fullPath: '/mail/static-mail-templates/$id/'
      preLoaderRoute: typeof DashboardMailStaticMailTemplatesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mail/dynamic-mail-templates/$id/': {
      id: '/_dashboard/mail/dynamic-mail-templates/$id/'
      path: '/$id'
      fullPath: '/mail/dynamic-mail-templates/$id/'
      preLoaderRoute: typeof DashboardMailDynamicMailTemplatesIdIndexRouteImport
      parentRoute: typeof DashboardMailDynamicMailTemplatesRoute
    }
    '/_dashboard/mail/static-mail-templates/$id/edit': {
      id: '/_dashboard/mail/static-mail-templates/$id/edit'
      path: '/mail/static-mail-templates/$id/edit'
      fullPath: '/mail/static-mail-templates/$id/edit'
      preLoaderRoute: typeof DashboardMailStaticMailTemplatesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardMailDynamicMailTemplatesRouteChildren {
  DashboardMailDynamicMailTemplatesCreateRoute: typeof DashboardMailDynamicMailTemplatesCreateRoute
  DashboardMailDynamicMailTemplatesIndexRoute: typeof DashboardMailDynamicMailTemplatesIndexRoute
  DashboardMailDynamicMailTemplatesIdIndexRoute: typeof DashboardMailDynamicMailTemplatesIdIndexRoute
}

const DashboardMailDynamicMailTemplatesRouteChildren: DashboardMailDynamicMailTemplatesRouteChildren =
  {
    DashboardMailDynamicMailTemplatesCreateRoute:
      DashboardMailDynamicMailTemplatesCreateRoute,
    DashboardMailDynamicMailTemplatesIndexRoute:
      DashboardMailDynamicMailTemplatesIndexRoute,
    DashboardMailDynamicMailTemplatesIdIndexRoute:
      DashboardMailDynamicMailTemplatesIdIndexRoute,
  }

const DashboardMailDynamicMailTemplatesRouteWithChildren =
  DashboardMailDynamicMailTemplatesRoute._addFileChildren(
    DashboardMailDynamicMailTemplatesRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMailAllMailsRoute: typeof DashboardMailAllMailsRoute
  DashboardMailDynamicMailTemplatesRoute: typeof DashboardMailDynamicMailTemplatesRouteWithChildren
  DashboardMasterAreasRoute: typeof DashboardMasterAreasRoute
  DashboardMasterBranchesRoute: typeof DashboardMasterBranchesRoute
  DashboardMasterDepartmentsRoute: typeof DashboardMasterDepartmentsRoute
  DashboardMasterPositionsRoute: typeof DashboardMasterPositionsRoute
  DashboardMasterStaffsRoute: typeof DashboardMasterStaffsRoute
  DashboardSystemRolesRoute: typeof DashboardSystemRolesRoute
  DashboardSystemUsersRoute: typeof DashboardSystemUsersRoute
  DashboardMailStaticMailTemplatesCreateRoute: typeof DashboardMailStaticMailTemplatesCreateRoute
  DashboardMailStaticMailTemplatesIndexRoute: typeof DashboardMailStaticMailTemplatesIndexRoute
  DashboardMailStaticMailTemplatesIdEditRoute: typeof DashboardMailStaticMailTemplatesIdEditRoute
  DashboardMailStaticMailTemplatesIdIndexRoute: typeof DashboardMailStaticMailTemplatesIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMailAllMailsRoute: DashboardMailAllMailsRoute,
  DashboardMailDynamicMailTemplatesRoute:
    DashboardMailDynamicMailTemplatesRouteWithChildren,
  DashboardMasterAreasRoute: DashboardMasterAreasRoute,
  DashboardMasterBranchesRoute: DashboardMasterBranchesRoute,
  DashboardMasterDepartmentsRoute: DashboardMasterDepartmentsRoute,
  DashboardMasterPositionsRoute: DashboardMasterPositionsRoute,
  DashboardMasterStaffsRoute: DashboardMasterStaffsRoute,
  DashboardSystemRolesRoute: DashboardSystemRolesRoute,
  DashboardSystemUsersRoute: DashboardSystemUsersRoute,
  DashboardMailStaticMailTemplatesCreateRoute:
    DashboardMailStaticMailTemplatesCreateRoute,
  DashboardMailStaticMailTemplatesIndexRoute:
    DashboardMailStaticMailTemplatesIndexRoute,
  DashboardMailStaticMailTemplatesIdEditRoute:
    DashboardMailStaticMailTemplatesIdEditRoute,
  DashboardMailStaticMailTemplatesIdIndexRoute:
    DashboardMailStaticMailTemplatesIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthSsoRoute: AuthSsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
